# Spring config
spring:
  mvc:
    static-path-pattern: /static
    throw-exception-if-no-handler-found: true
  logging:
    level:
      org.springframework.boot.autoconfigure.jdbc: DEBUG
      com.zaxxer.hikari: DEBUG
  servlet:
    multipart:
      max-file-size: 6MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectdb?useSSL=false
    password: "1111"
    username: "projectuser"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    generate-ddl: true
    show-sql: true
